name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - name: Test using ts-jest
        run: npm run test:ts
      - name: Test using @swc/jest
        run: npm run test:swc

